disallowed-types = [
    "std::sync::Mutex",
    "std::sync::RwLock",
    "parking_lot::Mutex",
    "parking_lot::RwLock",
    "arc_swap::ArcSwap",
    "std::collections::HashMap"
]

disallowed-methods = [
    "std::thread::sleep"
]
